<?php

return [
	'inp' => [
		'title'              => 'INP',
		'slug'               => 'inp',
		'status'             => 'publish',
		'core_area'          => 'Technisches Fundament',
		'index_policy'       => 'index',
		'excerpt'              => 'Wie schnell reagiert eine Website auf einen Klick, ein Tippen oder eine Tastatureingabe?',
		'short_definition'     => 'INP steht für Interaction to Next Paint. Der Wert beschreibt, wie lange eine Website nach einer Eingabe bis zur nächsten sichtbaren Reaktion braucht.',
		'why_it_matters'       => 'Eine Seite kann schnell laden und sich trotzdem träge bedienen lassen. Wenn ein Menü erst verspätet aufgeht oder ein Formular scheinbar nicht reagiert, klicken Besucher womöglich mehrfach oder brechen ab.',
		'measurement'          => 'INP berücksichtigt Klicks, Tippen und Tastatureingaben während eines Besuchs. Maßgeblich ist eine der langsamsten Interaktionen, bei vielen Eingaben werden einzelne Ausreißer ausgeklammert. Ein reiner Ladetest ohne Interaktion liefert keinen INP.',
		'benchmarks'           => [
			[
				'label' => 'Gut',
				'value' => 'bis 200 ms',
			],
			[
				'label' => 'Verbessern',
				'value' => 'über 200 bis 500 ms',
			],
			[
				'label' => 'Schlecht',
				'value' => 'über 500 ms',
			],
		],
		'mistakes'             => [
			'Zu viel JavaScript blockiert den Browser bei Eingaben.',
			'Nur den Seitenstart testen und Menüs oder Formulare übersehen.',
		],
		'primary_url_key'    => 'cwv',
		'primary_url_label'  => 'Core Web Vitals',
		'related_primary_urls' => [
			[
				'key' => 'home',
				'label' => 'WordPress-Entwicklung & Performance',
			],
		],
		'related_terms'      => [ 'lcp', 'cls', 'ttfb' ],
		'seo_title'          => 'INP: Definition, gute Werte und typische Bremsen | Haşim Üner',
		'seo_description'      => 'Wie schnell reagiert eine Website auf einen Klick, ein Tippen oder eine Tastatureingabe? Verständlich erklärt mit Beispiel und typischen Fehlern.',
		'example'              => [
			'text' => 'Sie tippen auf „Menü“. Die Navigation öffnet sich erst nach einer halben Sekunde. Diese Verzögerung fließt in den INP ein. Gemessen wird bis zur nächsten Bildausgabe, nicht bis zum Abschluss einer späteren Serverantwort.',
		],
		'measurement_label'    => 'Welche INP-Werte sind gut?',
		'benchmark_note'       => 'Mindestens 75 % der Besuche sollten den guten Wert erreichen. Mobil und Desktop getrennt prüfen.',
		'search_terms'       => [
			'INP',
			'Interaction to Next Paint',
			'Reaktionszeit',
		],
		'sources'              => [
			[
				'label' => 'Google: Interaction to Next Paint',
				'url' => 'https://web.dev/articles/inp',
			],
		],
	],
	'lcp' => [
		'title'            => 'LCP',
		'slug'             => 'lcp',
		'status'           => 'publish',
		'core_area'        => 'Technisches Fundament',
		'index_policy'     => 'index',
		'excerpt'              => 'Wann erscheint der größte sichtbare Inhalt beim Öffnen einer Seite?',
		'short_definition'     => 'LCP steht für Largest Contentful Paint. Er misst die Zeit vom Aufruf einer Seite bis zur Anzeige ihres größten sichtbaren Inhalts – häufig ein Bild oder ein Textblock.',
		'why_it_matters'       => 'Besucher sollen schnell erkennen, was eine Seite bietet. Erscheint der Hauptinhalt spät, warten sie auf ein Bild oder eine Überschrift, obwohl andere Teile bereits sichtbar sind.',
		'measurement'          => 'PageSpeed Insights zeigt nach Möglichkeit Messungen echter Besucher und einen separaten Labortest. Das LCP-Element kann auf dem Smartphone ein anderes sein als am Desktop. Der Wert sagt nicht, wann die gesamte Seite fertig geladen ist.',
		'benchmarks'           => [
			[
				'label' => 'Gut',
				'value' => 'bis 2,5 s',
			],
			[
				'label' => 'Verbessern',
				'value' => 'über 2,5 bis 4 s',
			],
			[
				'label' => 'Schlecht',
				'value' => 'über 4 s',
			],
		],
		'mistakes'             => [
			'Das große Einstiegsbild unnötig spät laden, etwa durch Lazy Loading.',
			'Nur Bilder verkleinern und eine langsame Serverantwort oder blockierende Ressourcen übersehen.',
		],
		'primary_url_key'  => 'cwv',
		'primary_url_label'=> 'Core Web Vitals',
		'related_primary_urls' => [
			[
				'key' => 'home',
				'label' => 'WordPress-Entwicklung & Performance',
			],
		],
		'related_terms'    => [ 'inp', 'cls', 'ttfb' ],
		'seo_title'        => 'LCP: Definition, gute Werte und typische Bremsen | Haşim Üner',
		'seo_description'      => 'Wann erscheint der größte sichtbare Inhalt beim Öffnen einer Seite? Verständlich erklärt mit Beispiel und typischen Fehlern.',
		'example'              => [
			'text' => 'Oben auf einer Angebotsseite steht ein großes Foto. Die Navigation ist sofort sichtbar, das Foto erscheint erst nach vier Sekunden. Ist dieses Foto das größte relevante Element im sichtbaren Bereich, liegt der LCP ungefähr bei vier Sekunden.',
		],
		'measurement_label'    => 'Welche LCP-Werte sind gut?',
		'benchmark_note'       => 'Bei mindestens 75 % der Seitenaufrufe sollte der LCP höchstens 2,5 Sekunden betragen. Mobil und Desktop getrennt betrachten.',
		'search_terms'       => [
			'LCP',
			'Largest Contentful Paint',
			'Ladezeit',
		],
		'sources'              => [
			[
				'label' => 'Google: Largest Contentful Paint',
				'url' => 'https://web.dev/articles/lcp',
			],
		],
	],
	'cls' => [
		'title'            => 'CLS',
		'slug'             => 'cls',
		'status'           => 'publish',
		'core_area'        => 'Technisches Fundament',
		'index_policy'     => 'index',
		'excerpt'              => 'Wie stark springen Inhalte während des Seitenbesuchs unerwartet hin und her?',
		'short_definition'     => 'CLS steht für Cumulative Layout Shift. Der Wert beschreibt, wie stark sich sichtbare Inhalte unerwartet verschieben. Er berücksichtigt sowohl die betroffene Fläche als auch die Entfernung der Verschiebung.',
		'why_it_matters'       => 'Ein springendes Layout unterbricht das Lesen. Besonders störend ist es, wenn ein Button kurz vor dem Klick seine Position verändert und Besucher das falsche Element treffen.',
		'measurement'          => 'CLS ist eine Zahl ohne Zeiteinheit. Gezählt wird die stärkste Gruppe aufeinanderfolgender Layout-Verschiebungen während des Besuchs. Das betrifft auch nachgeladene Inhalte nach dem ersten Seitenaufbau.',
		'benchmarks'           => [
			[
				'label' => 'Gut',
				'value' => 'bis 0,1',
			],
			[
				'label' => 'Verbessern',
				'value' => 'über 0,1 bis 0,25',
			],
			[
				'label' => 'Schlecht',
				'value' => 'über 0,25',
			],
		],
		'mistakes'             => [
			'Bei Bildern, Videos oder eingebetteten Inhalten keinen Platz reservieren.',
			'Hinweise nachträglich über bestehende Inhalte schieben.',
		],
		'primary_url_key'  => 'cwv',
		'primary_url_label'=> 'Core Web Vitals',
		'related_primary_urls' => [
			[
				'key' => 'home',
				'label' => 'WordPress-Entwicklung & Performance',
			],
		],
		'related_terms'    => [ 'inp', 'lcp', 'message-match' ],
		'seo_title'        => 'CLS: Definition, gute Werte und typische Ursachen | Haşim Üner',
		'seo_description'      => 'Wie stark springen Inhalte während des Seitenbesuchs unerwartet hin und her? Verständlich erklärt mit Beispiel und typischen Fehlern.',
		'example'              => [
			'text' => 'Sie wollen auf „Angebot anfragen“ tippen. Darüber lädt nachträglich ein Bild ohne reservierten Platz. Der Button rutscht nach unten und Ihr Finger trifft einen anderen Link. Solche unerwarteten Verschiebungen erhöhen den CLS.',
		],
		'measurement_label'    => 'Welche CLS-Werte sind gut?',
		'benchmark_note'       => 'Für eine gute Bewertung sollten mindestens 75 % der Besuche bei höchstens 0,1 liegen. Ein kurzer Labortest kann spätere Verschiebungen übersehen.',
		'search_terms'       => [
			'CLS',
			'Cumulative Layout Shift',
			'Layout-Verschiebung',
		],
		'sources'              => [
			[
				'label' => 'Google: Cumulative Layout Shift',
				'url' => 'https://web.dev/articles/cls',
			],
		],
	],
	'ttfb' => [
		'title'            => 'TTFB',
		'slug'             => 'ttfb',
		'status'           => 'publish',
		'core_area'        => 'Technisches Fundament',
		'index_policy'     => 'index',
		'excerpt'              => 'Wie lange wartet der Browser auf das erste Byte einer Antwort?',
		'short_definition'     => 'TTFB steht für Time to First Byte. Gemessen wird die Zeit vom Beginn einer Anfrage bis zum ersten Byte der Antwort. Dazu können auch Weiterleitungen, Verbindungsaufbau und Netzwerkzeiten gehören.',
		'why_it_matters'       => 'Bevor die erste Antwort ankommt, kann der Browser mit dem Seiteninhalt kaum etwas anfangen. Eine lange Wartezeit verzögert deshalb oft auch die sichtbare Darstellung.',
		'measurement'          => 'Google nennt 0,8 Sekunden oder weniger als grobe Orientierung für die meisten Websites. TTFB ist kein Core Web Vital. Ein guter Wert allein bedeutet deshalb noch keine schnelle oder gut bedienbare Website.',
		'benchmarks'           => [
			[
				'label' => 'Gut',
				'value' => 'bis 0,8 s',
			],
			[
				'label' => 'Verbessern',
				'value' => 'über 0,8 bis 1,8 s',
			],
			[
				'label' => 'Schlecht',
				'value' => 'über 1,8 s',
			],
		],
		'mistakes'             => [
			'TTFB mit der gesamten Ladezeit verwechseln.',
			'Nur einen Aufruf mit warmem Cache messen und langsame ungecachte Aufrufe übersehen.',
		],
		'primary_url_key'      => 'cwv',
		'primary_url_label'    => 'WordPress-Performance',
		'related_primary_urls' => [
			[
				'key' => 'home',
				'label' => 'WordPress-Entwicklung & Performance',
			],
		],
		'related_terms'    => [ 'inp', 'lcp', 'cls' ],
		'seo_title'        => 'TTFB: Definition, Ursachen und Einordnung | Haşim Üner',
		'seo_description'      => 'Wie lange wartet der Browser auf das erste Byte einer Antwort? Verständlich erklärt mit Beispiel und typischen Fehlern.',
		'example'              => [
			'text' => 'Eine WordPress-Seite antwortet nach 1,2 Sekunden, ihr großes Bild erscheint nach 2,8 Sekunden. Die TTFB beträgt 1,2 Sekunden. Die Zeit bis zur Anzeige des Bildes ist eine andere Messung – möglicherweise der LCP.',
		],
		'measurement_label'    => 'Wie lässt sich TTFB einordnen?',
		'benchmark_note'       => 'Orientierungswerte, keine allgemeine Bestehensgrenze. Netzwerk, Cache und Seitentyp beeinflussen die Messung.',
		'search_terms'       => [
			'TTFB',
			'Time to First Byte',
			'Server-Antwortzeit',
		],
		'sources'              => [
			[
				'label' => 'Google: Time to First Byte',
				'url' => 'https://web.dev/articles/ttfb',
			],
		],
	],
	'canonical-url' => [
		'title'            => 'Canonical URL',
		'slug'             => 'canonical-url',
		'status'           => 'publish',
		'core_area'        => 'Sichtbarkeit',
		'index_policy'     => 'index',
		'excerpt'              => 'Welche URL soll bei gleichen oder sehr ähnlichen Seiten bevorzugt werden?',
		'short_definition'     => 'Eine Canonical URL ist die bevorzugte Adresse eines Inhalts. Mit einem Canonical-Tag können Sie Suchmaschinen darauf hinweisen, welche Version bei gleichen oder sehr ähnlichen Seiten maßgeblich sein soll.',
		'why_it_matters'       => 'Ein Inhalt kann unter mehreren Adressen erreichbar sein, etwa mit und ohne Kampagnenparameter. Eine konsistente Kennzeichnung hilft Suchmaschinen, diese Versionen zusammenzufassen.',
		'measurement'          => 'Der Canonical-Tag ist ein starkes Signal, aber keine Anweisung, die Google zwingend übernimmt. Er leitet Besucher nicht weiter und verhindert keinen Seitenaufruf. In der Search Console lässt sich die von Google gewählte kanonische URL prüfen.',
		'mistakes'             => [
			'Auf eine gelöschte, gesperrte oder inhaltlich andere Seite verweisen.',
			'Canonical, Sitemap und interne Links auf unterschiedliche Versionen ausrichten.',
			'Den Canonical als Ersatz für eine nötige Weiterleitung verwenden.',
		],
		'primary_url_key'  => 'seo',
		'primary_url_label'=> 'WordPress SEO Hannover',
		'related_primary_urls' => [
			[
				'key' => 'home',
				'label' => 'WordPress-Entwicklung & technisches SEO',
			],
		],
		'related_terms'        => [
			'utm-parameter',
		],
		'seo_title'        => 'Canonical URL: Definition und typische Fehler | Haşim Üner',
		'seo_description'      => 'Welche URL soll bei gleichen oder sehr ähnlichen Seiten bevorzugt werden? Verständlich erklärt mit Beispiel und typischen Fehlern.',
		'example'              => [
			'text' => 'Eine Leistungsseite ist unter /angebot/ und /angebot/?utm_source=newsletter erreichbar. Beide zeigen denselben Inhalt. Im Quelltext kann die Adresse ohne Parameter als bevorzugte Version angegeben werden. Die Beispiel-Domain ist ein Platzhalter.',
			'code' => '<link rel="canonical" href="https://example.com/angebot/">',
		],
		'measurement_label'    => 'Was bewirkt ein Canonical?',
		'sources'              => [
			[
				'label' => 'Google Search Central: kanonische URLs',
				'url' => 'https://developers.google.com/search/docs/crawling-indexing/consolidate-duplicate-urls?hl=de',
			],
		],
	],
	'utm-parameter' => [
		'title'            => 'UTM-Parameter',
		'slug'             => 'utm-parameter',
		'status'           => 'publish',
		'core_area'        => 'Messbarkeit',
		'index_policy'     => 'index',
		'excerpt'              => 'Zusätze im Link zeigen, aus welcher Kampagne ein Websitebesuch kommt.',
		'short_definition'     => 'UTM-Parameter sind Zusätze an einer URL. Sie kennzeichnen zum Beispiel Quelle, Kanal und Kampagne, damit ein Analysetool Besuche entsprechend zuordnen kann.',
		'why_it_matters'       => 'Sie verschicken Links per Newsletter und teilen sie auf LinkedIn. Einheitliche UTM-Parameter helfen dabei, die Besuche dieser Aktionen zu unterscheiden. Ob daraus Anfragen werden, muss zusätzlich gemessen werden.',
		'measurement'          => 'Verwenden Sie feste Namen und eine einheitliche Schreibweise. „LinkedIn“ und „linkedin“ können als unterschiedliche Quellen erscheinen. Prüfen Sie nach einem Testklick, ob Ihr Analysetool die Angaben tatsächlich erhält. Der Link allein richtet noch kein Tracking ein.',
		'mistakes'             => [
			'Interne Links mit Kampagnenparametern versehen und dadurch die Auswertung verfälschen.',
			'Namen oder E-Mail-Adressen in die URL schreiben.',
			'Parameter durch Weiterleitungen verlieren.',
		],
		'primary_url_key'  => 'tracking',
		'primary_url_label'=> 'GA4 Tracking Setup',
		'related_primary_urls' => [
			[
				'key' => 'tracking',
				'label' => 'GA4-Tracking einrichten',
			],
		],
		'related_terms'        => [
			'canonical-url',
			'owned-leads',
		],
		'seo_title'        => 'UTM-Parameter: Definition, Aufbau und typische Fehler | Haşim Üner',
		'seo_description'      => 'Zusätze im Link zeigen, aus welcher Kampagne ein Websitebesuch kommt. Verständlich erklärt mit Beispiel und typischen Fehlern.',
		'example'              => [
			'text' => 'Ein Link aus einem Newsletter könnte so aussehen. Die Domain dient nur als Beispiel:',
			'code' => 'https://example.com/angebot/?utm_source=newsletter&utm_medium=email&utm_campaign=website-check',
			'items' => [
				'utm_source=newsletter' => 'Quelle: der eigene Newsletter',
				'utm_medium=email' => 'Kanal: E-Mail',
				'utm_campaign=website-check' => 'Name der Aktion: Website-Check',
			],
		],
		'measurement_label'    => 'Worauf kommt es an?',
		'search_terms'       => [
			'UTM-Parameter',
			'UTM',
			'Kampagnenquelle',
			'Kampagnenparameter',
		],
		'sources'              => [
			[
				'label' => 'Google Analytics: Kampagnen-URLs',
				'url' => 'https://support.google.com/analytics/answer/10917952?hl=de',
			],
		],
	],
	'message-match' => [
		'title'            => 'Message Match',
		'slug'             => 'message-match',
		'status'           => 'publish',
		'core_area'        => 'Conversion',
		'index_policy'     => 'index',
		'excerpt'              => 'Passt die Zielseite zu dem Versprechen, auf das jemand geklickt hat?',
		'short_definition'     => 'Message Match bedeutet: Eine Zielseite greift das Versprechen der Anzeige, E-Mail oder des Links auf, über den ein Besucher kommt. Er erkennt sofort, dass er hier richtig ist.',
		'why_it_matters'       => 'Wer nach einer bestimmten Leistung sucht, möchte sie auf der Zielseite wiederfinden. Muss er sich das Angebot erst zusammensuchen, entsteht unnötige Unsicherheit.',
		'measurement'          => 'Lesen Sie Anzeige und Zielseite direkt hintereinander. Stimmen Leistung, Zielgruppe, Konditionen und nächster Schritt überein? Wortgleiche Überschriften sind dafür nicht nötig. Entscheidend ist, dass die Seite das geweckte Versprechen tatsächlich einlöst.',
		'mistakes'             => [
			'Alle Anzeigen auf dieselbe allgemeine Startseite schicken.',
			'Einen Festpreis ankündigen und auf der Zielseite nur „Preis auf Anfrage“ nennen.',
			'Für ein konkretes Angebot werben, das auf dem Smartphone erst weit unten erscheint.',
		],
		'keywords_match'   => [ 'Message Match', 'Anzeigen-Anschluss', 'Erwartungskonformität' ],
		'primary_url_key'  => 'cro',
		'primary_url_label'=> 'Conversion Rate Optimization',
		'related_primary_urls' => [
			[
				'key' => 'cro',
				'label' => 'Anfragestrecken & Landingpages',
			],
		],
		'related_terms'        => [
			'cta-hierarchie',
			'lead-qualifizierung',
			'conversion-rate-optimization',
		],
		'seo_title'        => 'Message Match: Definition und Bedeutung für CRO | Haşim Üner',
		'seo_description'      => 'Passt die Zielseite zu dem Versprechen, auf das jemand geklickt hat? Verständlich erklärt mit Beispiel und typischen Fehlern.',
		'example'              => [
			'text' => 'Eine Anzeige verspricht „WordPress-Wartung zum Festpreis“. Die Zielseite sollte genau diese Wartung erklären: enthaltene Leistungen, Preis und nächster Schritt. Eine allgemeine Agentur-Startseite mit „Wir machen Sie digital erfolgreich“ beantwortet diese Erwartung kaum.',
		],
		'measurement_label'    => 'So prüfen Sie den Zusammenhang',
		'sources'              => [],
	],
	'lead-qualifizierung' => [
		'title'            => 'Lead-Qualifizierung',
		'slug'             => 'lead-qualifizierung',
		'status'           => 'publish',
		'core_area'        => 'Conversion',
		'index_policy'     => 'index',
		'excerpt'              => 'Welche Anfragen passen zu Ihrem Angebot und brauchen als Nächstes ein Gespräch?',
		'short_definition'     => 'Lead-Qualifizierung bedeutet, eine Anfrage anhand festgelegter Kriterien einzuordnen. Ein Lead ist dabei zunächst ein Kontakt mit erkennbarem Interesse – noch kein Auftrag.',
		'why_it_matters'       => 'Zehn Formularanfragen können sehr unterschiedlich wertvoll sein. Klare Kriterien helfen, passende Projekte zügig zu bearbeiten und bei offenen Fragen gezielt nachzufassen.',
		'measurement'          => 'Fragen Sie nur ab, was die nächste Entscheidung verändert: Bedarf, fachliche Passung, Zeitrahmen und gegebenenfalls Budget. Marketing und Vertrieb sollten dieselbe Vorstellung davon haben, wann ein Kontakt als qualifiziert gilt.',
		'mistakes'             => [
			'Jeden Formularabschluss als qualifizierte Anfrage zählen.',
			'Viele Pflichtfelder einbauen, deren Antworten später niemand verwendet.',
			'Kontakte wegen fehlender Angaben automatisch verwerfen, obwohl eine Rückfrage reichen würde.',
		],
		'keywords_match'   => [ 'Lead-Qualifizierung', 'Leadqualifizierung', 'Lead Qualification', 'qualifizierter Lead', 'qualifizierte Leads' ],
		'primary_url_key'  => 'cro',
		'primary_url_label'=> 'Conversion & Anfragearchitektur',
		'related_primary_urls' => [
			[
				'key' => 'cro',
				'label' => 'Anfragestrecken & Landingpages',
			],
		],
		'related_terms'        => [
			'owned-leads',
			'message-match',
			'cta-hierarchie',
		],
		'seo_title'        => 'Lead-Qualifizierung im B2B: Definition & Praxis | Haşim Üner',
		'seo_description'      => 'Welche Anfragen passen zu Ihrem Angebot und brauchen als Nächstes ein Gespräch? Verständlich erklärt mit Beispiel und typischen Fehlern.',
		'example'              => [
			'text' => 'Ein Betrieb sucht eine neue Website. Im Formular nennt er die bestehende URL, den gewünschten Umfang und einen Zeitrahmen. Diese Angaben helfen zu entscheiden, ob ein Erstgespräch sinnvoll ist oder vorher noch etwas geklärt werden muss.',
		],
		'measurement_label'    => 'Welche Kriterien helfen?',
		'sources'              => [],
	],
	'cta-hierarchie' => [
		'title'            => 'CTA-Hierarchie',
		'slug'             => 'cta-hierarchie',
		'status'           => 'publish',
		'core_area'        => 'Conversion',
		'index_policy'     => 'noindex',
		'excerpt'              => 'Eine klare Rangfolge zeigt, welche Handlung auf einer Seite im Vordergrund steht.',
		'short_definition'     => 'CTA steht für Call to Action, also eine Handlungsaufforderung wie „Angebot anfragen“. CTA-Hierarchie beschreibt, wie die wichtigste Aktion sichtbar von weiteren Möglichkeiten unterschieden wird.',
		'why_it_matters'       => 'Wenn Anfrage, Download und Newsletter gleich auffällig sind, fehlt eine klare Orientierung. Eine erkennbare Rangfolge hilft Besuchern, den nächsten Schritt einzuordnen.',
		'measurement'          => 'Betrachten Sie jeden Abschnitt einzeln: Ist klar, was Besucher hier tun können? Passt die Aktion zu den Informationen, die sie bisher bekommen haben? Mehr Klicks auf den Hauptbutton helfen nur, wenn anschließend auch passende Anfragen entstehen.',
		'mistakes'             => [
			'Mehrere unterschiedlich wichtige Aktionen identisch gestalten.',
			'Kontakt verlangen, bevor Leistung und Nutzen verständlich sind.',
			'Hilfreiche Alternativen so unauffällig machen, dass sie kaum erkennbar bleiben.',
		],
		'keywords_match'   => [ 'CTA-Hierarchie', 'CTA Hierarchie', 'primärer CTA', 'sekundärer CTA', 'primäre Handlung', 'sekundäre Handlung' ],
		'primary_url_key'  => 'cro',
		'primary_url_label'=> 'Conversion & Anfragearchitektur',
		'related_primary_urls' => [
			[
				'key' => 'cro',
				'label' => 'Anfragestrecken & Landingpages',
			],
		],
		'related_terms'        => [
			'message-match',
			'lead-qualifizierung',
			'conversion-rate-optimization',
		],
		'seo_title'        => 'CTA-Hierarchie: Primäre und sekundäre CTAs | Haşim Üner',
		'seo_description'      => 'Eine klare Rangfolge zeigt, welche Handlung auf einer Seite im Vordergrund steht. Verständlich erklärt mit Beispiel und typischen Fehlern.',
		'example'              => [
			'text' => 'Auf einer Leistungsseite ist „Projekt anfragen“ der hervorgehobene Button. „Arbeiten ansehen“ steht daneben als zurückhaltender Link. Wer schon überzeugt ist, kann anfragen; wer noch einen Beleg sucht, findet ihn ebenfalls.',
		],
		'measurement_label'    => 'So prüfen Sie Ihre Seite',
		'sources'              => [],
	],
	'owned-leads' => [
		'title'            => 'Owned Leads',
		'slug'             => 'owned-leads',
		'status'           => 'publish',
		'core_area'        => 'Strategie',
		'index_policy'     => 'index',
		'excerpt'              => 'Anfragen über die eigene Website und eigene Kontaktwege gewinnen.',
		'short_definition'     => 'Owned Leads bezeichnet hier Anfragen, die über Ihre eigene Website oder andere selbst verwaltete Kontaktwege eingehen. Sie gestalten das Formular, die Erfassung und die weitere Bearbeitung selbst.',
		'why_it_matters'       => 'Der Vorteil liegt in der Kontrolle über den Anfrageweg. Sie können Informationen passend abfragen und im eigenen CRM weiterbearbeiten. Reichweite, Pflege und Werbung verursachen trotzdem Aufwand und Kosten.',
		'measurement'          => 'Website, Formular und Kundensystem sollten zusammenpassen und für Sie zugänglich sein. Prüfen Sie, woher Anfragen kommen und welche zu passenden Projekten führen. „Owned“ beschreibt dabei die Kontrolle über den Prozess, kein Eigentum an Menschen oder uneingeschränkte Nutzungsrechte an Daten.',
		'mistakes'             => [
			'Eigene Anfragen mit kostenloser oder ausschließlich organischer Reichweite gleichsetzen.',
			'Die gesamte Strecke auf Konten aufbauen, auf die der Betrieb keinen Zugriff hat.',
			'Viele Anfragen sammeln, ohne ihre Qualität zu prüfen.',
		],
		'keywords_match'   => [ 'Owned Leads', 'eigene Leads', 'kontrollierte Nachfrage', 'Portal-Unabhängigkeit' ],
		'primary_url_key'  => 'wgos',
		'primary_url_label'=> 'Anfragesystem-Methode',
		'related_primary_urls' => [
			[
				'key' => 'cro',
				'label' => 'Anfragestrecken & Landingpages',
			],
		],
		'related_terms'        => [
			'lead-qualifizierung',
			'utm-parameter',
			'message-match',
		],
		'seo_title'        => 'Owned Leads: Bedeutung und strategische Einordnung | Haşim Üner',
		'seo_description'      => 'Anfragen über die eigene Website und eigene Kontaktwege gewinnen. Verständlich erklärt mit Beispiel und typischen Fehlern.',
		'example'              => [
			'text' => 'Ein Interessent klickt auf Ihre Google-Anzeige und fragt über Ihr Websiteformular an. Diese Anfrage zählt hier zu Owned Leads, obwohl der Besuch bezahlt war. Einen von einem Portal gekauften Kontakt haben Sie dagegen nicht über diesen eigenen Weg gewonnen.',
		],
		'measurement_label'    => 'Was gehört zum eigenen Anfrageweg?',
		'sources'              => [],
	],
	'solar-leadgenerierung' => [
		'title'              => 'Solar Leadgenerierung',
		'slug'               => 'solar-leadgenerierung',
		'status'             => 'publish',
		'core_area'          => 'Strategie',
		'index_policy'       => 'alias',
		'excerpt'              => 'Interessenten für Photovoltaik-Anlagen gewinnen und in konkrete Anfragen führen.',
		'short_definition'     => 'Solar-Leadgenerierung bedeutet, Kontakte mit Interesse an Photovoltaik zu gewinnen, etwa über die eigene Website, Anzeigen oder Vermittlungsportale.',
		'why_it_matters'       => 'Entscheidend ist, welche Anfragen zum Einzugsgebiet und Angebot passen.',
		'keywords_match'     => [ 'B2B-Leadgenerierung für Solar', 'Leadgenerierung für Photovoltaik', 'Leadgenerierung für Solar', 'Leadgenerierung für Solarteure', 'Photovoltaik Leadgenerierung', 'Photovoltaik-Leadgenerierung', 'Solar Leadgenerierung', 'Solar-Leadgenerierung', 'PV Leadgenerierung', 'PV-Leadgenerierung', 'Photovoltaik Leads', 'Photovoltaik-Leads', 'Solar Leads', 'Solar-Leads', 'PV Leads', 'PV-Leads', 'Wärmepumpen Leads', 'Wärmepumpen-Leads', 'qualifizierte PV-Anfragen', 'qualifizierte Solar-Anfragen', 'eigene Solar-Anfragen', 'Anfragesystem für Solar', 'Anfragesysteme für Solar', 'Anfragesystem Solar', 'Solar-Kundengewinnung', 'Kundengewinnung für Solarteure' ],
		'primary_url_key'    => 'energy',
		'primary_url_label'  => 'Solar- und Wärmepumpen-Leadgenerierung',
		'related_primary_urls' => [],
		'related_terms'      => [ 'owned-leads', 'lead-portale', 'message-match' ],
		'seo_title'          => 'Solar Leadgenerierung | Haşim Üner',
		'seo_description'      => 'Solar-Leadgenerierung erklärt: Interessenten für Photovoltaik gewinnen und passende Anfragen bearbeiten.',
		'sources'              => [],
	],
	'lead-portale' => [
		'title'              => 'Lead-Portale',
		'slug'               => 'lead-portale',
		'status'             => 'publish',
		'core_area'          => 'Strategie',
		'index_policy'       => 'alias',
		'excerpt'              => 'Plattformen vermitteln Kundenanfragen an Anbieter – je nach Tarif exklusiv oder an mehrere Betriebe.',
		'short_definition'     => 'Lead-Portale sammeln Anfragen von Interessenten und vermitteln sie gegen Bezahlung an passende Anbieter. Ob ein Kontakt exklusiv ist oder geteilt wird, hängt vom Angebot ab.',
		'why_it_matters'       => 'Kosten, Passung und Bearbeitungsaufwand bestimmen, ob ein vermittelter Kontakt wirtschaftlich sinnvoll ist.',
		'keywords_match'     => [ 'Lead-Portale', 'Leadportale', 'Portal-Leads', 'Leads kaufen', 'Photovoltaik Leads kaufen', 'Solarleads', 'Lead-Anbieter', 'Vergleichsportal', 'Vergleichsportale', 'Portal-Abhängigkeit', 'Wattfox', 'Aroundhome', 'DAA' ],
		'primary_url_key'    => 'solar_leads_alternative',
		'primary_url_label'  => 'Solar Leads kaufen Alternative',
		'related_primary_urls' => [],
		'related_terms'      => [ 'owned-leads', 'message-match' ],
		'seo_title'          => 'Lead-Portale für Solar & SHK: Risiken und Alternativen | Haşim Üner',
		'seo_description'    => 'Warum das Kaufen von Leads bei Portalen zu Margendruck führt und wie B2B-Anbieter durch eigene Systeme unabhängiger werden.',
		'sources'              => [],
	],
	'wordpress-agentur-hannover' => [
		'title'              => 'WordPress Agentur Hannover',
		'slug'               => 'wordpress-agentur-hannover',
		'status'             => 'publish',
		'core_area'          => 'Sichtbarkeit',
		'index_policy'       => 'alias',
		'excerpt'              => 'WordPress-Websites in der Region Hannover entwickeln und betreuen lassen.',
		'short_definition'     => 'Eine WordPress-Agentur plant, entwickelt oder betreut Websites mit WordPress. Der Zusatz Hannover bezeichnet die gesuchte Region.',
		'why_it_matters'     => 'Der lokale Money-Intent soll nicht in einem Glossarartikel hängen bleiben, sondern direkt auf die passende B2B-Landingpage führen.',
		'keywords_match'     => [ 'WordPress Agentur Hannover', 'B2B WordPress Agentur', 'WordPress Agentur Region Hannover', 'WordPress Entwickler Hannover' ],
		'primary_url_key'    => 'agentur',
		'primary_url_label'  => 'WordPress Agentur Hannover',
		'related_primary_urls' => [],
		'related_terms'      => [ 'canonical-url', 'message-match', 'utm-parameter' ],
		'seo_title'          => 'WordPress Agentur Hannover: B2B Anfragesysteme | Haşim Üner',
		'seo_description'    => 'Architektur und Digitalstrategie für WordPress im DACH-Raum mit lokalem Fokus auf Hannover und Umgebung.',
		'show_in_hub'          => false,
		'sources'              => [],
	],
	'core-web-vitals' => [
		'title'              => 'Core Web Vitals',
		'slug'               => 'core-web-vitals',
		'status'             => 'publish',
		'core_area'          => 'Technisches Fundament',
		'index_policy'       => 'alias',
		'excerpt'              => 'Drei Messwerte für Ladegeschwindigkeit, Reaktionszeit und visuelle Stabilität einer Website.',
		'short_definition'     => 'Die Core Web Vitals sind drei Messwerte für die Nutzung einer Website: LCP beschreibt die Ladegeschwindigkeit, INP die Reaktion auf Eingaben und CLS unerwartete Layout-Verschiebungen.',
		'primary_url_key'    => 'cwv',
		'primary_url_label'  => 'Core Web Vitals Cluster',
		'seo_title'          => 'Core Web Vitals | Haşim Üner',
		'seo_description'      => 'Core Web Vitals einfach erklärt: LCP, INP und CLS messen zentrale Aspekte der Website-Nutzung.',
		'sources'              => [],
		'related_primary_urls' => [],
	],
	'conversion-rate-optimization' => [
		'title'              => 'Conversion Rate Optimization',
		'slug'               => 'conversion-rate-optimization',
		'status'             => 'publish',
		'core_area'          => 'Conversion',
		'index_policy'       => 'alias',
		'excerpt'              => 'Eine Website so verbessern, dass mehr Besucher die gewünschte Handlung ausführen.',
		'short_definition'     => 'Conversion Rate Optimization (CRO) bedeutet Conversion-Optimierung: Inhalte, Bedienung und Abläufe so verbessern, dass ein größerer Anteil der Besucher die gewünschte Handlung ausführt, etwa eine passende Anfrage sendet.',
		'primary_url_key'    => 'cro',
		'primary_url_label'  => 'Conversion Rate Optimization',
		'seo_title'          => 'Conversion Rate Optimization | Haşim Üner',
		'seo_description'      => 'Conversion-Optimierung erklärt: Inhalte und Abläufe einer Website gezielt verbessern und die Wirkung messen.',
		'sources'              => [],
		'related_primary_urls' => [],
	],
];
